import { BoardState } from '@/types/board';

export const INITIAL_BOARD_DATA: BoardState = {
  version: 1,
  baseStartDate: '2026-09-01',
  sprintDurationWeeks: 2,
  sprints: [
    {
      id: 'sprint-0',
      number: 0,
      order: 0,
      title: 'Sprint 0 — Discovery e Arquitetura',
      subtitle: 'Alinhamento inicial, modelagem e especificações',
      durationWeeks: 2,
      customDateLabel: '1 a 2 semanas',
      isMvp: true,
      notes: 'Planejamento e fundação arquitetural do projeto.',
      tasks: [
        { id: 't0-1', title: 'Refinar requisitos com o cliente', status: 'done', category: 'funcionalidade', assignedTo: 'Designer / Produto' },
        { id: 't0-2', title: 'Mapear regras de negócio da mentoria', status: 'done', category: 'funcionalidade', assignedTo: 'Designer / Produto' },
        { id: 't0-3', title: 'Definição da stack tecnológica (Next.js + NestJS/Spring)', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't0-4', title: 'Modelagem do banco de dados relacional', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't0-5', title: 'Wireframes e prototipação de alta fidelidade', status: 'done', category: 'frontend', assignedTo: 'Designer / Produto' },
        { id: 't0-6', title: 'Mapeamento do fluxo completo da plataforma', status: 'done', category: 'funcionalidade', assignedTo: 'Designer / Produto' },
        { id: 't0-7', title: 'Documento funcional estruturado', status: 'done', category: 'entregavel', assignedTo: 'Designer / Produto' },
        { id: 't0-8', title: 'Fluxos de usuário desenhados', status: 'done', category: 'entregavel', assignedTo: 'Designer / Produto' },
        { id: 't0-9', title: 'Arquitetura técnica documentada', status: 'done', category: 'entregavel', assignedTo: 'Dev 1' },
        { id: 't0-10', title: 'Backlog priorizado em sprints', status: 'done', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-1',
      number: 1,
      order: 1,
      title: 'Sprint 1 — Fundação da Plataforma',
      subtitle: 'Estrutura base de autenticação, perfis e design system',
      durationWeeks: 2,
      customDateLabel: '2 semanas',
      isMvp: true,
      notes: 'Base essencial de usuários, segurança e identidade visual.',
      tasks: [
        { id: 't1-1', title: 'Autenticação JWT / Sessões seguras', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't1-2', title: 'Gestão de Perfis (Aluno / Admin)', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't1-3', title: 'Fluxo de recuperação de senha por e-mail', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't1-4', title: 'Controle de permissões (RBAC)', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't1-5', title: 'Design System & Paleta de Cores Institucional', status: 'done', category: 'frontend', assignedTo: 'Designer / Produto' },
        { id: 't1-6', title: 'Layout base responsivo e componentes UI', status: 'done', category: 'frontend', assignedTo: 'Dev 2' },
        { id: 't1-7', title: 'Estrutura PWA configurada', status: 'done', category: 'frontend', assignedTo: 'Dev 2' },
        { id: 't1-8', title: 'Navegação e roteamento de telas', status: 'done', category: 'frontend', assignedTo: 'Dev 2' },
        { id: 't1-9', title: 'Entregável: Telas de Login & Cadastro finalizadas', status: 'done', category: 'entregavel', assignedTo: 'Dev 2' },
        { id: 't1-10', title: 'Entregável: Tela de Recuperação de Senha', status: 'done', category: 'entregavel', assignedTo: 'Dev 2' },
        { id: 't1-11', title: 'Entregável: Dashboard vazio inicial acessível', status: 'done', category: 'entregavel', assignedTo: 'Dev 2' },
      ],
    },
    {
      id: 'sprint-2',
      number: 2,
      order: 2,
      title: 'Sprint 2 — Gestão de Cursos (Admin)',
      subtitle: 'Base do sistema: Criação e estrutura pedagógica de cursos',
      durationWeeks: 2,
      customDateLabel: '17 - 31 de setembro',
      isMvp: true,
      notes: 'Base do sistema. Tudo depende disso.',
      tasks: [
        { id: 't2-1', title: 'CRUD completo de cursos', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't2-2', title: 'Gestão de Categorias de cursos', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't2-3', title: 'Estrutura de Módulos vinculados', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't2-4', title: 'Cadastro e ordenação de Aulas', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't2-5', title: 'Upload e gestão de Materiais complementares', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't2-6', title: 'Painel administrativo de gestão de cursos', status: 'done', category: 'frontend', assignedTo: 'Dev 2' },
        { id: 't2-7', title: 'Formulários dinâmicos de criação e edição', status: 'todo', category: 'frontend', assignedTo: 'Dev 2' },
        { id: 't2-8', title: 'Entregável: Admin cria cursos completos (falta parte de simulados/questões)', status: 'in_progress', category: 'entregavel', notes: 'Falta conectar com a parte de simulados e questões', assignedTo: 'Dev 1' },
      ],
    },
    {
      id: 'sprint-3',
      number: 3,
      order: 3,
      title: 'Sprint 3 — Site Público + Catálogo 20%',
      subtitle: 'Vitrine pública, páginas promocionais e catálogo inicial',
      durationWeeks: 2,
      customDateLabel: '31 - 14 de setembro',
      isMvp: true,
      notes: 'Porta de entrada pública para captação e apresentação.',
      tasks: [
        { id: 't3-1', title: 'Home institucional com seções de mentoria', status: 'done', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't3-2', title: 'Catálogo de cursos com listagem dinâmica', status: 'done', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't3-3', title: 'Página detalhada de produto / curso', status: 'done', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't3-4', title: 'Sistema de busca em tempo real', status: 'done', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't3-5', title: 'Filtros avançados (categorias, modalidades)', status: 'done', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't3-6', title: 'Entregável: Site público 100% funcionando', status: 'done', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-4',
      number: 4,
      order: 4,
      title: 'Sprint 4 — Banco de Questões e Simulados',
      subtitle: 'Coração do estudo de lei seca: Questões e resolução de simulados',
      durationWeeks: 2,
      customDateLabel: '14 - 28 de setembro',
      isMvp: true,
      notes: 'Uma das sprints mais pesadas e cruciais para a proposta de valor.',
      tasks: [
        { id: 't4-1', title: 'Modelagem do Banco de Questões', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't4-2', title: 'Categorias de Questões', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't4-3', title: 'Disciplinas jurídicas cadastradas', status: 'done', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't4-4', title: 'Mecanismo de criação e geração de simulados', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't4-5', title: 'Geração automática de questões por tópico', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't4-6', title: 'Motor de correção instantânea e gabarito comentado', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't4-7', title: 'Histórico de tentativas e métricas do aluno', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't4-8', title: 'Entregável: Simulados funcionando ponta a ponta', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-5',
      number: 5,
      order: 5,
      title: 'Sprint 5 — Área do Aluno',
      subtitle: 'Ambiente exclusivo dos mentorados: Acesso aos cursos e dashboard',
      durationWeeks: 2,
      customDateLabel: '28 de setembro - 12 de outubro',
      isMvp: true,
      notes: 'Experiência interna do aluno matriculado.',
      tasks: [
        { id: 't5-1', title: 'Dashboard do aluno com métricas e avisos', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't5-2', title: 'Área "Meus Cursos" matriculados', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't5-3', title: 'Página interna do curso com grade de aulas', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't5-4', title: 'Indicador visual de progresso percentual', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't5-5', title: 'Entregável: Aluno consegue acessar e navegar pelos cursos', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-6',
      number: 6,
      order: 6,
      title: 'Sprint 6 — Tela de Estudos (Fim do MVP)',
      subtitle: 'Player de vídeo, leitor de PDFs com CPF protegido e conclusões',
      durationWeeks: 2,
      customDateLabel: '12 - 26 de outubro',
      isMvp: true,
      notes: 'Finaliza o escopo de entrega do MVP (Primeiro lançamento oficial!).',
      tasks: [
        { id: 't6-1', title: 'Player de vídeo integrado com controle de reprodução', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't6-2', title: 'Leitor e download de PDFs com marca d\'água de CPF', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't6-3', title: 'Exibição formatada de artigos e textos de lei', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't6-4', title: 'Links externos e materiais de apoio', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't6-5', title: 'Ação de marcar aula como concluída', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't6-6', title: 'Cálculo de progresso automático por módulo', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't6-7', title: 'Entregável: Consumo completo do conteúdo pelos alunos (MVP Pronto!)', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-7',
      number: 7,
      order: 7,
      title: 'Sprint 7 — Checkout e Vendas',
      subtitle: 'Integração financeira, pedidos e liberação automática de matrículas',
      durationWeeks: 2,
      customDateLabel: '26 de outubro - 09 de novembro',
      isMvp: false,
      notes: 'Início da Fase Comercial autônoma.',
      tasks: [
        { id: 't7-1', title: 'Integração de Gateway de pagamento (PIX / Cartão)', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't7-2', title: 'Gestão de Pedidos e Webhooks de confirmação', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't7-3', title: 'Histórico financeiro do usuário', status: 'todo', category: 'backend', assignedTo: 'Dev 1' },
        { id: 't7-4', title: 'Tela de Checkout transparente e segura', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't7-5', title: 'Processamento de aprovação automática', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't7-6', title: 'Liberação instantânea do curso após confirmação', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't7-7', title: 'Entregável: Compra funcionando ponta a ponta (Curso -> Checkout -> Acesso)', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-8',
      number: 8,
      order: 8,
      title: 'Sprint 8 — Ranking e Gamificação',
      subtitle: 'Gamificação, pontuação por simulados, rankings e engajamento',
      durationWeeks: 2,
      customDateLabel: '2 semanas',
      isMvp: false,
      notes: 'Diferencial competitivo para engajamento contínuo dos concurseiros.',
      tasks: [
        { id: 't8-1', title: 'Tabelas e visualização de Rankings gerais e por turma', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't8-2', title: 'Sistema de pontuação e medalhas / badges', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't8-3', title: 'Histórico detalhado de desempenho em simulados', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't8-4', title: 'Gráficos comparativos com a média dos candidatos', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't8-5', title: 'Entregável: Sistema de gamificação completo e ativo', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-9',
      number: 9,
      order: 9,
      title: 'Sprint 9 — Semanas de Simulado',
      subtitle: 'Cronogramas organizados por semana e jornadas estruturadas',
      durationWeeks: 2,
      customDateLabel: '2 semanas',
      isMvp: false,
      notes: 'Estruturação pedagógica de simulados semanais.',
      tasks: [
        { id: 't9-1', title: 'Módulo de Cronogramas de estudos por data', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't9-2', title: 'Organização de conteúdo e metas por semana', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't9-3', title: 'Associação de simulados específicos para cada semana', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't9-4', title: 'Agendamento de publicação e abertura de simulados', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't9-5', title: 'Entregável: Jornada de estudo semanal estruturada', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-10',
      number: 10,
      order: 10,
      title: 'Sprint 10 — Administração Avançada',
      subtitle: 'Gestão de alunos, relatórios de vendas, comunicados e CRM',
      durationWeeks: 2,
      customDateLabel: '2 semanas',
      isMvp: false,
      notes: 'Ferramentas completas para a mentora operar o negócio.',
      tasks: [
        { id: 't10-1', title: 'Painel completo de Gestão de Alunos', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't10-2', title: 'Painel de Gestão e Relatórios de Vendas', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 1' },
        { id: 't10-3', title: 'Mural de Comunicados e avisos aos mentorados', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't10-4', title: 'Dashboard Administrativo consolidado com KPIs', status: 'todo', category: 'funcionalidade', assignedTo: 'Dev 2' },
        { id: 't10-5', title: 'Entregável: Operação completa da mentora autônoma', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
    {
      id: 'sprint-11',
      number: 11,
      order: 11,
      title: 'Sprint 11 — Migração e Go Live',
      subtitle: 'Migração de dados do Bubble, testes de carga e lançamento oficial',
      durationWeeks: 2,
      customDateLabel: '2 semanas',
      isMvp: false,
      notes: 'Sprint essencial de homologação, segurança e corte final.',
      tasks: [
        { id: 't11-1', title: 'Migração de banco de Alunos (Bubble -> Nova Plataforma)', status: 'todo', category: 'migracao', assignedTo: 'Dev 1' },
        { id: 't11-2', title: 'Migração e validação de Cursos e Estrutura', status: 'todo', category: 'migracao', assignedTo: 'Dev 1' },
        { id: 't11-3', title: 'Migração em lote de Questões e Gabaritos', status: 'todo', category: 'migracao', assignedTo: 'Dev 1' },
        { id: 't11-4', title: 'Importação do Histórico necessário de matrículas', status: 'todo', category: 'migracao', assignedTo: 'Dev 1' },
        { id: 't11-5', title: 'Testes de Carga e Estresse no servidor', status: 'todo', category: 'testes', assignedTo: 'Dev 1' },
        { id: 't11-6', title: 'Auditoria de Segurança e permissões de arquivos', status: 'todo', category: 'testes', assignedTo: 'Dev 1' },
        { id: 't11-7', title: 'Homologação final com a cliente e mentora', status: 'todo', category: 'testes', assignedTo: 'Designer / Produto' },
        { id: 't11-8', title: 'Entregável: Plataforma Completa em Produção (Go Live!)', status: 'todo', category: 'entregavel', assignedTo: 'Geral' },
      ],
    },
  ],
  quickNotes: [
    {
      id: 'qn-1',
      title: 'Definir gateway de pagamento prioritário para a Sprint 7',
      description: 'Avaliar taxas e facilidade de integração PIX com Asaas, Stripe ou MercadoPago.',
      type: 'question_client',
      status: 'open',
      priority: 'high',
      createdAt: '2026-08-25T17:00:00.000Z',
    },
    {
      id: 'qn-2',
      title: 'Formato exato e layout do CPF em marca d\'água nos PDFs',
      description: 'Confirmar com o cliente se deve ser no rodapé de todas as páginas ou texto diagonal translúcido.',
      type: 'question_client',
      status: 'open',
      priority: 'medium',
      createdAt: '2026-08-25T17:05:00.000Z',
    },
    {
      id: 'qn-3',
      title: 'Regras de pontuação para o Ranking de Simulados',
      description: 'Definir se acertos em questões difíceis ganham mais pontos ou pontuação simples 1 para 1.',
      type: 'question_client',
      status: 'open',
      priority: 'medium',
      createdAt: '2026-08-25T17:10:00.000Z',
    },
    {
      id: 'qn-4',
      title: 'Melhoria: Adicionar filtro rápido por banca examinadora nas questões',
      description: 'Sugestão de UX para facilitar concurseiros que buscam questões específicas da FGV ou Cebraspe.',
      type: 'improvement',
      status: 'open',
      priority: 'medium',
      createdAt: '2026-08-25T17:15:00.000Z',
    },
    {
      id: 'qn-5',
      title: 'Revisar responsividade da barra de navegação no mobile',
      description: 'Garantir que o menu drawer abra suavemente em telas menores que 380px.',
      type: 'bug',
      status: 'open',
      priority: 'low',
      createdAt: '2026-08-25T17:20:00.000Z',
    },
  ],
};
